### ISSUE TITLE
Language support while editing code blocks within a markdown file

### ISSUE THREAD

**Issue by kieferrm** [kieferrm/vscode-markdown#1]
From https://github.com/Microsoft/vscode/issues/6106

we need to investigate how to support embedded languages in the markdown editor (not for the preview, this is for the source) so that code blocks get colored properly. according to @aeschli TM supports the notion of referencing other grammars from within a grammar. ideally we could reference our installed TM bundles for any code block that is being used in the markdown source

In addition to syntax highlighting this includes code folding and simple intellisense.

**Comment by kieferrm** [comment]
@aeschli do you have an example of how a TM grammar referencing another TM grammar?

**Comment by aeschli** [comment]
In your language's grammar you can include grammars of other languages.
See https://manual.macromates.com/en/language_grammars, 12.3 Rule Keys, 'include'.

You can see that in action in a jade.file:

``` jade
p #[code samp] — Regular text. #[samp This is sample text] more text.

-if(typeof(info) !== 'undefined')
  p Conditional text.
```

The coloring of the 'if' clause is driven by the javascript grammar. To see the scopes each token gets, use the developer tools: Inspect HTML element.

![image](https://cloud.githubusercontent.com/assets/6461412/15174919/387f5bde-1764-11e6-96a6-e464949d3fe8.png)

You can see that the token contains `js` in the scope. It comes from a rule that is defined in `vscode/extensions/javascript/syntaxes/JavaScript.tmLanguage`

To see how this is done in the Jade grammar, check the Jade grammar `vscode/extensions/jade/syntaxes/Jade.tmLanguage` and look for `include source.js` in the `Unbuffered code block` rule

**Comment by kieferrm** [comment]
Changes rely on  https://github.com/Microsoft/vscode-textmate/tree/kieferrm/support-while.
