### ISSUE TITLE
Automatically update preview while changing the markdown source

### ISSUE THREAD

**Issue by kieferrm** [kieferrm/vscode-markdown#2]
From https://github.com/Microsoft/vscode/issues/6106:

we need to change the extension to update the preview based on document edits so that the preview updates while the user is typing

**Comment by kieferrm** [comment]
Here is our initial thinking for how to update the side-by-side preview: 
1. The extension is listening to the document change events emitted by the workspace
1. If we receive a document change event for a markdown document we translate that into a document change event for the virtual markdown preview document and let the registered document content provider fire that document change event
1. Ensure the html preview editor reloads when it receives a document changed event from the document content provider

**Comment by bpasero** [comment]
I think that is the idea, also @jrieken fyi who provides the API for text document provider.

**Comment by jrieken** [comment]
Yes - your document provider can offer an [event](https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.d.ts#L1065) that signals [change](https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.d.ts#L1138). This is an sample: https://github.com/Microsoft/vscode/blob/master/extensions/vscode-api-tests/src/workspace.test.ts#L299

**Comment by kieferrm** [comment]
@jrieken thanks. That's makes for a slick solution.
