### ISSUE TITLE
Style markdown preview 

### ISSUE THREAD

**Issue by kieferrm** [kieferrm/vscode-markdown#3]
From https://github.com/Microsoft/vscode/issues/6106:

we need to finish the CSS styling for the preview so that it is in sync with what we have today and also works in dark and light theme and any other theme from extensions (also depends on https://github.com/Microsoft/vscode/issues/5737)

**Comment by kieferrm** [comment]
One of the issue we have is to let the extension know whether the active theme is a dark or a light theme. This information is not available.  We'll introduce a command that the extension can call and the command will return the information.

How to implement this:
- register internal command in src/vs/workbench/electro-browser/action.ts (there are other possibilities where to register the command but this is our best guess for now)
- the command is a stripped down version of src/vs/workbench/parts/themes/test/electron-browser/themes.test.contribution.ts
- register API command in extHostAPICommands.ts so that it is available as a public api

The extension uses the command similarly to:
vscode/extensions/vscode-colorize-tests/src/colorizer.test.ts

**Comment by kieferrm** [comment]
https://github.com/kieferrm/vscode/commit/cc5d971d7dfe6b23c2ad56b37826e6835a2097d7 implements the vscode core changes.  https://github.com/kieferrm/vscode-markdown/tree/Styling contains the current state on the extension side. 

Investigating display issues between webview and iframe.

**Comment by kieferrm** [comment]
htmlPreviewPart.ts injects a bunch of default styles onto the displayed html:

```
        body {
            margin: 0;
        }

        * {
            color: ${color};
            background-color: ${backgroundColor};
            font-family: ${fontFamily};
            font-size: ${fontSize};
        }

        img {
            max-width: 100%;
            max-height: 100%;
        }
        a:focus,
        input:focus,
        select:focus,
        textarea:focus {
            outline: 1px solid -webkit-focus-ring-color;
            outline-offset: -1px;
        }
```

Particularly the \* selector is harmful as it violates all assumptions of how you usually structure your css-rules. Need to discuss, why it is there in the first place.

**Comment by bpasero** [comment]
@jrieken fyi

**Comment by jrieken** [comment]
The force is some default styles cos not every is aware of dark and light theme ;-) I know the `*` selector is bad but at least we make sure those rules come first so that subsequent css rules have a change to overrule them. 

Ideas for May is to play with css variables Chrome has introduced and by default use them to style the body element

**Comment by kieferrm** [comment]
The current state:
- We only style the body element and ensure those styles are overridden by any style defined by the html source.
- We transparently add a class to the body element that indicates the active theme:  **vs** (for light), **vs-dark** (for dark), **hc-black** for high contrast.
