### ISSUE TITLE
Links to local #id don't work in html preview

### ISSUE THREAD

**Issue by kieferrm** [kieferrm/vscode-markdown#9]
<a href="#section2">click</a> don't work in the html preview even when section2 exists. This seems to be an issue with the webview.

**Comment by rebornix** [comment]
1. markdown-it doesn't support header anchor, which means, there is no id set for headers. See issues here https://github.com/markdown-it/markdown-it/issues/28 and the only workaround for now is adding plugins. 
2. Even if there is an anchor generated successfully, the default behavior of clicking #id (we call it bookmark) in an iframe inside a webview is opening the file again. So it will try to load `file:///c%3A/Users/penlv/code/testmd/#synchronization`, which is not accessible.
3. We are checking if people are clicking on bookmarks by `if (node.tagName === 'A' && node.href && node.href[0] !== '#') {`, however, `node.href` contains file name, eg, `file:///c%3A/Users/penlv/code/testmd/#synchronization`, `node.href[0] !== '#'` is always true. The correct attribute we should check is `node.hash` per http://www.w3schools.com/jsref/prop_anchor_hash.asp
4. `scrollIntoView` works here perfectly.

**Comment by kieferrm** [comment]
Resolved by commit https://github.com/kieferrm/vscode/commit/521500ae48cdf2c76e62745c728f5f9763444021
